name: flutter_web_markdown
author: Flutter Authors <flutter-dev@googlegroups.com>
description: A Markdown renderer for Flutter.
homepage: https://github.com/alex-misch/flutter_web_markdown
version: 0.2.0

dependencies:
  flutter_web: any
  flutter_web_ui: any
  markdown: ^2.0.0
  meta: ^1.0.5
  string_scanner: ^1.0.0
  path: ^1.5.1

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

dev_dependencies:
  mockito: ^3.0.0
  # Enables the `pub run build_runner` command
  build_runner: ">=1.6.2 <2.0.0"
  # Includes the JavaScript compilers
  build_web_compilers: ">=1.2.0 <3.0.0"

environment:
  sdk: ">=2.3.0 <3.0.0"
